name = "HeisenHeatbath"
uuid = "c665481f-c81f-4649-8d1e-3441473abd7e"
authors = ["PatXue <95881915+PatXue@users.noreply.github.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
